version: '3'

services:

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=courses
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
    - ./DB/UDEMYDBCOURS.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - backend

  ads-main:
    build: .
    environment:
      - JAVA_OPTS= -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n
      - PORT=5000
    depends_on:
      - db
    ports:
      - 5000:5000
    networks:
      - backend

networks:
  backend:
